"""Update user table and add company to user to role table

Revision ID: 0488948a6d8f
Revises: 287d8647da30
Create Date: 2025-06-29 10:11:55.672544

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0488948a6d8f"
down_revision: Union[str, None] = "287d8647da30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "CompanyUser",
        "UserID",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.add_column(
        "User",
        sa.Column("DefaultCompanyDetailsID", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "User",
        sa.Column("IsPaid", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_foreign_key(
        None,
        "User",
        "CompanyDetails",
        ["DefaultCompanyDetailsID"],
        ["CompanyDetailsID"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="foreignkey")
    op.drop_column("User", "IsPaid")
    op.drop_column("User", "DefaultCompanyDetailsID")
    op.alter_column(
        "CompanyUser",
        "UserID",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=36),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
