"""add amount to subscriptions

Revision ID: 06a4ac5d0f3b
Revises: c398f5395ce5
Create Date: 2025-08-26 20:03:08.866861

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06a4ac5d0f3b"
down_revision: Union[str, None] = "c398f5395ce5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PaymentSubscriptions", sa.Column("Amount", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("PaymentSubscriptions", "Amount")
    # ### end Alembic commands ###
