"""create payment tables

Revision ID: 12836889d8d4
Revises: 885e339403c2
Create Date: 2025-07-21 11:21:37.380075

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12836889d8d4"
down_revision: Union[str, None] = "885e339403c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PaymentSubscriptions",
        sa.Column("SubscriptionID", sa.String(length=36), nullable=False),
        sa.Column("PayerID", sa.String(length=255), nullable=False),
        sa.Column("BeneficiaryID", sa.String(length=255), nullable=False, unique=True),
        sa.Column("RazorpaySubscriptionID", sa.String(length=100), nullable=False),
        sa.Column("RazorpayCustomerID", sa.String(length=100), nullable=False),
        sa.Column("Status", sa.String(length=50), nullable=True),
        sa.Column("StartDate", sa.DateTime(), nullable=False),
        sa.Column("EndDate", sa.DateTime(), nullable=False),
        sa.Column("NextBillingDate", sa.DateTime(), nullable=True),
        sa.Column("CreatedAt", sa.DateTime(), nullable=True),
        sa.Column("UpdatedAt", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["BeneficiaryID"],
            ["User.ClerkID"],
        ),
        sa.ForeignKeyConstraint(
            ["PayerID"],
            ["User.ClerkID"],
        ),
        sa.PrimaryKeyConstraint("SubscriptionID"),
    )
    op.create_index(
        op.f("ix_PaymentSubscriptions_BeneficiaryID"),
        "PaymentSubscriptions",
        ["BeneficiaryID"],
        unique=True,
    )
    op.create_index(
        op.f("ix_PaymentSubscriptions_PayerID"),
        "PaymentSubscriptions",
        ["PayerID"],
        unique=False,
    )
    op.create_table(
        "Payments",
        sa.Column("PaymentID", sa.String(length=36), nullable=False),
        sa.Column("SubscriptionID", sa.String(length=36), nullable=False),
        sa.Column("RazorpayPaymentID", sa.String(length=100), nullable=False),
        sa.Column("Amount", sa.Float(), nullable=False),
        sa.Column("Currency", sa.String(length=10), nullable=True),
        sa.Column("Status", sa.String(length=50), nullable=True),
        sa.Column("Method", sa.String(length=50), nullable=True),
        sa.Column("InvoiceID", sa.String(length=100), nullable=True),
        sa.Column("Description", sa.String(length=255), nullable=True),
        sa.Column("CreatedAt", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["SubscriptionID"],
            ["PaymentSubscriptions.SubscriptionID"],
        ),
        sa.PrimaryKeyConstraint("PaymentID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Payments")
    op.drop_index(
        op.f("ix_PaymentSubscriptions_PayerID"), table_name="PaymentSubscriptions"
    )
    op.drop_index(
        op.f("ix_PaymentSubscriptions_BeneficiaryID"), table_name="PaymentSubscriptions"
    )
    op.drop_table("PaymentSubscriptions")
    # ### end Alembic commands ###
