"""Initial migration

Revision ID: 287d8647da30
Revises: 
Create Date: 2024-06-17 12:30:07.574609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287d8647da30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Organization')
    op.drop_index('ix_User_ClerkID', table_name='User')
    op.create_unique_constraint(None, 'User', ['ClerkID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_index('ix_User_ClerkID', 'User', ['ClerkID'], unique=True)
    op.create_table('Organization',
    sa.Column('OrganizationID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('OrganizationName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('UserID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='Organization_UserID_fkey'),
    sa.PrimaryKeyConstraint('OrganizationID', name='Organization_pkey')
    )
    # ### end Alembic commands ###
