"""add unique constraint to CompanyUser

Revision ID: 46019e9d1f26
Revises: 0488948a6d8f
Create Date: 2025-06-29 11:32:51.733278

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46019e9d1f26"
down_revision: Union[str, None] = "0488948a6d8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_CompanyUser_CompanyID"), "CompanyUser", ["CompanyID"], unique=False
    )
    op.create_index(op.f("ix_CompanyUser_ID"), "CompanyUser", ["ID"], unique=False)
    op.create_index(
        op.f("ix_CompanyUser_UserID"), "CompanyUser", ["UserID"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_company", "CompanyUser", ["UserID", "CompanyID"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_company", "CompanyUser", type_="unique")
    op.drop_index(op.f("ix_CompanyUser_UserID"), table_name="CompanyUser")
    op.drop_index(op.f("ix_CompanyUser_ID"), table_name="CompanyUser")
    op.drop_index(op.f("ix_CompanyUser_CompanyID"), table_name="CompanyUser")
    # ### end Alembic commands ###
