"""add non-nullable constraint on default company id

Revision ID: 885e339403c2
Revises: 46019e9d1f26
Create Date: 2025-07-02 10:41:23.679166

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "885e339403c2"
down_revision: Union[str, None] = "46019e9d1f26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "DefaultCompanyDetailsID",
        existing_type=sa.VARCHAR(length=36),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "DefaultCompanyDetailsID",
        existing_type=sa.VARCHAR(length=36),
        nullable=True,
    )
    # ### end Alembic commands ###
