"""add currency to subscriptions

Revision ID: b765d8c4dae1
Revises: 06a4ac5d0f3b
Create Date: 2025-08-27 14:38:19.270512

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b765d8c4dae1"
down_revision: Union[str, None] = "06a4ac5d0f3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "PaymentSubscriptions",
        sa.Column("Currency", sa.String(length=10), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("PaymentSubscriptions", "Currency")
    # ### end Alembic commands ###
