"""Initial migration

Revision ID: ff1569140517
Revises: 287d8647da30
Create Date: 2024-06-17 12:48:41.175596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1569140517'
down_revision: Union[str, None] = '287d8647da30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Currency',
    sa.Column('CurrencyID', sa.String(length=36), nullable=False),
    sa.Column('Currency', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CurrencyID')
    )
    op.create_table('Role',
    sa.Column('RoleID', sa.String(length=36), nullable=False),
    sa.Column('UserRole', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    op.create_table('CompanyDetails',
    sa.Column('CompanyDetailsID', sa.String(length=36), nullable=False),
    sa.Column('DisplayName', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('LegalName', sa.String(length=255), nullable=False),
    sa.Column('RegistrationNumber', sa.String(length=50), nullable=False),
    sa.Column('VatNumber', sa.String(length=50), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('City', sa.String(length=100), nullable=False),
    sa.Column('Country', sa.String(length=100), nullable=False),
    sa.Column('Zip', sa.String(length=20), nullable=False),
    sa.Column('CurrencyID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['CurrencyID'], ['Currency.CurrencyID'], ),
    sa.PrimaryKeyConstraint('CompanyDetailsID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.String(length=36), nullable=False),
    sa.Column('ClerkID', sa.String(length=36), nullable=False),
    sa.Column('UserName', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('RoleID', sa.String(length=36), nullable=False),
    sa.Column('CompanyDetailsID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['CompanyDetailsID'], ['CompanyDetails.CompanyDetailsID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['Role.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('ClerkID')
    )
    op.create_index(op.f('ix_User_Email'), 'User', ['Email'], unique=True)
    op.create_index(op.f('ix_User_UserName'), 'User', ['UserName'], unique=False)
    op.create_foreign_key(None, 'Commodity', 'CompanyDetails', ['CompanyDetailsID'], ['CompanyDetailsID'])
    op.create_foreign_key(None, 'MaterialGroup', 'CompanyDetails', ['CompanyDetailsID'], ['CompanyDetailsID'])
    op.create_foreign_key(None, 'PurchaseOrder', 'CompanyDetails', ['CompanyDetailsID'], ['CompanyDetailsID'])
    op.create_foreign_key(None, 'SourcingProject', 'CompanyDetails', ['CompanyDetailsID'], ['CompanyDetailsID'])
    op.create_foreign_key(None, 'Vendor', 'CompanyDetails', ['CompanyDetailsID'], ['CompanyDetailsID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vendor', type_='foreignkey')
    op.drop_constraint(None, 'SourcingProject', type_='foreignkey')
    op.drop_constraint(None, 'PurchaseOrder', type_='foreignkey')
    op.drop_constraint(None, 'MaterialGroup', type_='foreignkey')
    op.drop_constraint(None, 'Commodity', type_='foreignkey')
    op.drop_index(op.f('ix_User_UserName'), table_name='User')
    op.drop_index(op.f('ix_User_Email'), table_name='User')
    op.drop_table('User')
    op.drop_table('CompanyDetails')
    op.drop_table('Role')
    op.drop_table('Currency')
    # ### end Alembic commands ###
